name: Go Example
on:
  pull_request:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Go benchmark example
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
    - name: Run benchmark
      run: go test -bench=. ./... | tee output.txt
    - name: Download previous benchmark data
      uses: actions/cache@v1
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        # What benchmark tool the output.txt came from
        tool: 'go'
        # Where the output from the benchmark tool is stored
        output-file-path: output.txt
        # Where the previous data file is stored
        external-data-json-path: ./cache/benchmark-data.json
        # Workflow will fail when an alert happens
        fail-on-alert: true
        save-data-file: false
        comment-always: true
        github-token: ${{ secrets.GITHUB_TOKEN }}